### ISSUE TITLE
Show move category (special, physical, status)

### ISSUE THREAD

**Issue by karllhughes** [rowin1/Pokemon-Showdown-Enhanced-Tooltips#11]
I think this would be helpful as well. I [made a branch](https://github.com/karllhughes/Pokemon-Showdown-Enhanced-Tooltips/tree/tips), but I'm waiting to make my PR until #10 gets accepted.

**Comment by rowin1** [comment]
I agree that it would be helpful!  There are cases where Pokemon have a countering type but still take heavy damage due to low special defense or defense.  I've accepted #10 and would love to get this in as well. Thanks @karllhughes !  

P.S. Would you mind if I included your name on the Google chrome extension as a contributor?

**Comment by karllhughes** [comment]
@rowin1 awesome, thanks, and you are welcome to put me down as a contributor. When I have time, I love helping out on tools I find useful! 😃

I'll follow up with a PR for this and #12 later today.
